<?php

namespace TraderInteractive\SolrPopulator;

/**
 * An interface specifying operations for a raw ad record loader. Raw ad record
 * loaders load unprocessed ad data that could be generated by outside processes
 * and return's the data in a standardized key/value array format.
 */
interface RawAdRecordLoaderInterface
{
    public function getMappedAdRecords() : array;
}
